hide_download: true
hide_download_original: null
leftnav:
- identifier: 4849ebeb-09e7-de83-f30f-5d3c5cdf2cec
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: d936bcba-5b2b-6c50-7ea9-9b8e9207a3bc
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 64e728e0-0179-1042-61c4-67d8906d11bf
  name: Instructor Insights
  pageRef: /pages/instructor-insights/
  weight: 30
- identifier: da4b3356-07cc-777e-b267-a58ed3a4a5f8
  name: What is D-Lab?
  pageRef: /pages/instructor-insights/what-is-d-lab
  parent: 64e728e0-0179-1042-61c4-67d8906d11bf
  weight: 40
- identifier: 1ae5301e-7c2d-267a-4263-f163e997119a
  name: History and Development of the Course
  pageRef: /pages/instructor-insights/history-and-development-of-the-course
  parent: 64e728e0-0179-1042-61c4-67d8906d11bf
  weight: 50
- identifier: 40e1d48c-7e1d-3891-2dc5-a3fb01a39325
  name: Students as Teachers
  pageRef: /pages/instructor-insights/students-as-teachers
  parent: 64e728e0-0179-1042-61c4-67d8906d11bf
  weight: 60
- identifier: 9cc6a4e6-78b7-bd33-de2e-724464018b95
  name: Readings
  pageRef: /pages/readings/
  weight: 70
- identifier: f14ac857-fb37-82ec-0d52-77f42795ea1d
  name: Additional Readings
  pageRef: /pages/readings/additional-readings
  parent: 9cc6a4e6-78b7-bd33-de2e-724464018b95
  weight: 80
- identifier: 57b97a81-f4a6-3758-0cd6-a134df9061a9
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 90
- identifier: faa1c3a2-4b8a-65fd-1e0f-bef61250e637
  name: Assignments
  pageRef: /pages/assignments/
  weight: 100
- identifier: 23d843c9-3ebf-447e-36b7-d5d5f562bc61
  name: Projects
  pageRef: /pages/assignments/projects
  parent: faa1c3a2-4b8a-65fd-1e0f-bef61250e637
  weight: 110
- identifier: 4853e875-4de7-aade-3465-5cf11b481635
  name: Additional Resources
  pageRef: /pages/additional-resources/
  weight: 120
- identifier: 508f074e-c966-ba4d-4196-d946e41abbc7
  name: Climate & Climate Change
  pageRef: /pages/additional-resources/climate-climate-change
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 130
- identifier: 52d1eed2-91cd-c1b5-e878-892dfd6b1e1d
  name: Water & Oceans
  pageRef: /pages/additional-resources/water-oceans
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 140
- identifier: f8c16e55-96ce-1c5b-2d29-b1b554f00fc0
  name: Health
  pageRef: /pages/additional-resources/health
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 150
- identifier: 3cad5073-56c2-30ca-fd38-2a6889d09909
  name: Technology
  pageRef: /pages/additional-resources/technology
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 160
- identifier: 332b2b82-ac32-c07e-a220-660ae763f390
  name: Forestry & Agriculture
  pageRef: /pages/additional-resources/forestry-agriculture
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 170
- identifier: 91304eae-999c-bb46-6078-2e2ba5c836e9
  name: New England
  pageRef: /pages/additional-resources/new-england
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 180
- identifier: d9e9c320-906f-49c1-b2fb-1eb03c76ccdc
  name: Other
  pageRef: /pages/additional-resources/other
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 190
- identifier: 16e1cb0d-cd16-6b8d-7062-514796030100
  name: In the News
  pageRef: /pages/additional-resources/in-the-news
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 200
- identifier: 62d08d4d-9076-9bd4-7266-fe63ba1557f6
  name: Readings
  pageRef: /pages/additional-resources/readings
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 210
- identifier: 239732a6-7608-30c3-05dc-abfb991a111b
  name: Student Projects
  pageRef: /pages/additional-resources/student-projects
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 220
- identifier: 6b30a942-d5c5-94d5-77b3-afcbf6d48e8e
  name: Video & Audio
  pageRef: /pages/additional-resources/video-audio
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 230
- identifier: 212d1d54-7346-7c55-2089-e4021e6203e0
  name: Websites
  pageRef: /pages/additional-resources/websites
  parent: 4853e875-4de7-aade-3465-5cf11b481635
  weight: 240
